
development:
  adapter: postgresql
  encoding: unicode
  database: bscsails_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bscsails_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bscsails_production
  pool: 5
  username:
  password:
